# Site settings
title: The motherf... RBootcamp
description: The motherf... RBootcamp
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: TheRBootcamp
user_description: The motherf... RBootcamp
user_title: The motherf... RBootcamp
email: therbootcamp@gmail.com
twitter_username: therbootcamp
github_username:  therbootcamp

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
